# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

pr:
  branches:
    include:
    - '*'

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: AzureContainerApps@1
      inputs:
        appSourcePath: '.'
        azureSubscription: 'Azure subscription 1(1)(98cf1ccb-3209-459c-a9f3-98ffb07edab5)'
        acrName: 'dnstools'
        dockerfilePath: './Dockerfile'
        imageToBuild: 'dnstools.azurecr.io/dnstools:latest'
        imageToDeploy: 'dnstools.azurecr.io/dnstools:latest'
        containerAppName: 'dns-tools'
        resourceGroup: 'Example_pipelines'
        containerAppEnvironment: 'app-ghycbbyvsm6mo'
        runtimeStack: 'nodejs'
        targetPort: '3000'
        ingress: '80'